spring.application.name=payment-service
server.port=8085

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_payment_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Paypal
paypal.client-id=AQJm1o5o5VMyoQXosIgIcDuwLBVWrKgfp7F-WeP21XgrXYN190pXdBm2_ewDMvOhR1CiaSm9wCcouexp
paypal.client-secret=EMp2IGyuAG368EGOJ4B1PuyBqvRGaP4e86drkiZrfLdGZpsEeIhnAcIxpzpORxZ74_pNogUk-TAgbP6G
paypal.base-url=https://api-m.sandbox.paypal.com
paypal.return-url=http://localhost:5173/payment/success
paypal.cancel-url=http://localhost:5173/payment/cancel
paypal.currency=USD